export const GET_OPTIONS_SUCCESS = 'GET_OPTIONS_SUCCESS';
export const GET_DEFAULT_OPTIONS_SUCCESS = 'GET_DEFAULT_OPTIONS_SUCCESS';
export const REMOVE_DEFAULT_OPTION_SUCCESS = 'REMOVE_DEFAULT_OPTION_SUCCESS';
export const ADD_DEFAULT_OPTION_SUCCESS = 'ADD_DEFAULT_OPTION_SUCCESS';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';

export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
